#!/bin/sh -e

set -x

pytest --cov=starlette_auth --cov-report=xml
mypy starlette_auth --ignore-missing-imports
autoflake --recursive --remove-unused-variables starlette_auth tests
black starlette_auth tests --check
